IMPORTING NECESSARY LIBRARIES

In [1]:
import pandas as pd
import string
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download required NLTK data
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sussh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sussh\AppData\Roaming\nltk_data...

True

In [5]:
df = pd.read_csv("../Data/FinalDataset/Data.csv")
df.head()

,id,name,description,latitude,longitude,province,location,tags
0,1,Chapat Ganesh Mandir,Chapat Ganesh Temple is Ganesh temple located ...,27.671314,85.328967,Bagmati Province,Bagmati Province,"hindu, temple, pilgrimage"
1,2,Mayadevi Temple,Religious Site The Mayadevi temple is situated...,27.469641,83.275785,Lumbini Province,Lumbini Province,"buddhist, pilgrimage"
2,3,Sikali Mandir,Religious Site Sikali Temple lies in the south...,27.643535,85.285502,Bagmati Province,Kathmandu Valley,"hindu, temple, cultural"
3,4,Bala Guru Sadananda,Bala Guru Sadananda's shrine at his Ashram in ...,27.357001,87.137018,Koshi Province,Shadananda Municipality,"historical, monument"
4,5,21st Century Art Gallery,"21st Century Art Gallery, located in Kathmandu...",27.715548,85.309497,Bagmati Province,Kathmandu,"art_gallery, museum, cultural"

In [8]:
selected_columns = ['id', 'name', 'description', 'province', 'tags']
dataset = df[selected_columns]
dataset.columns = ['ID', 'Name', 'Description', 'Province', 'Tags']
dataset.head()

,ID,Name,Description,Province,Tags
0,1,Chapat Ganesh Mandir,Chapat Ganesh Temple is Ganesh temple located ...,Bagmati Province,"hindu, temple, pilgrimage"
1,2,Mayadevi Temple,Religious Site The Mayadevi temple is situated...,Lumbini Province,"buddhist, pilgrimage"
2,3,Sikali Mandir,Religious Site Sikali Temple lies in the south...,Bagmati Province,"hindu, temple, cultural"
3,4,Bala Guru Sadananda,Bala Guru Sadananda's shrine at his Ashram in ...,Koshi Province,"historical, monument"
4,5,21st Century Art Gallery,"21st Century Art Gallery, located in Kathmandu...",Bagmati Province,"art_gallery, museum, cultural"

CLEAN AND NORMALIZE TEXT

In [10]:
def clean_text(text):
    if pd.isnull(text):
        return text 
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Convert to lowercase
    text = text.lower()
    # Tokenize text
    tokens = word_tokenize(text)
    # Lemmatize tokens
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    # Join tokens back to string
    return ' '.join(tokens)

dataset['Description'] = dataset['Description'].apply(clean_text)
dataset['Tags'] = dataset['Tags'].apply(clean_text)

dataset.head()

C:\Users\sussh\AppData\Local\Temp\ipykernel_25852\3143449311.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Description'] = dataset['Description'].apply(clean_text)
C:\Users\sussh\AppData\Local\Temp\ipykernel_25852\3143449311.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Tags'] = dataset['Tags'].apply(clean_text)

,ID,Name,Description,Province,Tags
0,1,Chapat Ganesh Mandir,chapat ganesh temple is ganesh temple located ...,Bagmati Province,hindu temple pilgrimage
1,2,Mayadevi Temple,religious site the mayadevi temple is situated...,Lumbini Province,buddhist pilgrimage
2,3,Sikali Mandir,religious site sikali temple lie in the southe...,Bagmati Province,hindu temple cultural
3,4,Bala Guru Sadananda,bala guru sadanandas shrine at his ashram in d...,Koshi Province,historical monument
4,5,21st Century Art Gallery,21st century art gallery located in kathmandu ...,Bagmati Province,artgallery museum cultural

CHECK FOR MISSING VALUES

In [14]:
missing_value_rows = dataset[dataset.isnull().any(axis=1)]

# Display the IDs of rows with missing values
if 'ID' in missing_value_rows.columns:
    print("IDs of rows with missing values:")
    print(missing_value_rows['ID'].tolist())
else:
    print("The 'ID' column is not present in the dataset.")

IDs of rows with missing values:
[]

FINAL CHECK

In [15]:
print("Dataset Info:")
print(dataset.info())

print("\nSample Rows:")
print(dataset.head())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1862 entries, 0 to 1861
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           1862 non-null   int64
 1   Name         1862 non-null   object
 2   Description  1862 non-null   object
 3   Province     1862 non-null   object
 4   Tags         1862 non-null   object
dtypes: int64(1), object(4)
memory usage: 72.9+ KB
None

Sample Rows:
   ID                      Name  \
0   1      Chapat Ganesh Mandir
1   2           Mayadevi Temple
2   3             Sikali Mandir
3   4       Bala Guru Sadananda
4   5  21st Century Art Gallery

                                         Description          Province  \
0  chapat ganesh temple is ganesh temple located ...  Bagmati Province
1  religious site the mayadevi temple is situated...  Lumbini Province
2  religious site sikali temple lie in the southe...  Bagmati Province
3  bala guru sadanandas shrine at his ashram in d...    Koshi Province
4  21st century art gallery located in kathmandu ...  Bagmati Province

                         Tags
0     hindu temple pilgrimage
1         buddhist pilgrimage
2       hindu temple cultural
3         historical monument
4  artgallery museum cultural